---
title: дон Карлос
description: ''

timezone: Europe/Kiev
url: https://kastaneda.kiev.ua/
baseurl: ''

exclude:
  - Makefile
  - README
  - kastaneda.kiev.ua.tar.gz
  - build.sh

defaults:
  - scope:
      path: ''
    values:
      layout: FIXME-page
  - scope:
      type: posts
    values:
      layout: FIXME-page

collections:
  posts:
    title: Posts
    output: true

highlighter: rouge
