---
title: kastaneda.kiev.ua
description: ''

timezone: Europe/Kiev
url: https://kastaneda.kiev.ua/
baseurl: ''

exclude:
  - Makefile
  - README
  - kastaneda.kiev.ua.tar.gz
  - build.sh

defaults:
  - scope:
      path: ''
    values:
      layout: page

collections:
  posts:
    title: Posts
    output: true
#  uploads:
#    title: Uploads
#    output: true

highlighter: rouge
