---
title: kastaneda.kiev.ua
description: Дмитрий Колесников. Программист, веб-мастер, админ.

timezone: Europe/Kiev
url: https://kastaneda.kiev.ua
baseurl: ''

exclude:
  - Makefile
  - README
  - kastaneda.kiev.ua.tar.gz
  - build.sh

defaults:
  - scope:
      path: ''
    values:
      layout: page
  - scope:
      type: posts
    values:
      layout: post

collections:
  posts:
    title: Posts
    output: true

sass:
  style: compressed

highlighter: rouge
