---
title: kastaneda.kiev.ua
description: ''

timezone: Europe/Kiev
url: http://kastaneda.local
baseurl: /_site

exclude:
  - Makefile
  - README
  - kastaneda.kiev.ua.tar.gz
  - build.sh

defaults:
  - scope:
      path: ''
    values:
      layout: page

highlighter: rouge
